### ISSUE TITLE
Add domain validation. 

### ISSUE THREAD

**Issue by Bro05** [anviar/PKI#6]
Validation example by anviar:
`def valid_domain(input_domain):
   if not re.match('''^((?=[a-z0-9-]{1,63}\.)
                      (
                       [a-z0-9]+
                       |[a-z0-9][a-z0-9-]*[a-z0-9])*\.
                      )+([a-z]|xn--[a-z0-9-]+){2,63}$''',
                   input_domain.replace('*.', ''), re.VERBOSE):
           raise ArgumentTypeError('Неправильный ввод домена %s')
   return input_domain`

**Comment by ant0shik** [comment]
Resolved with [issue-6](https://github.com/anviar/PKI/tree/issue-6)
